// This file is auto-generated by scripts/generate.ts
// Do not edit manually.
import { Hono } from 'hono';

import { integrationsModule } from '../modules/integrations';
import { knowledgeBaseModule } from '../modules/knowledge-base';
import { messagingModule } from '../modules/messaging';
import { systemModule } from '../modules/system';

// Type-only chain — mirrors createApp() route mounting but preserves Hono's literal types.
// This function is never called at runtime.
function _typedApp() {
  return new Hono()
    .get('/health', (c) => c.json({ status: 'ok' as const, uptime: 0 }))
    .route('/api/integrations', integrationsModule.routes)
    .route('/api/knowledge-base', knowledgeBaseModule.routes)
    .route('/api/messaging', messagingModule.routes)
    .route('/api/system', systemModule.routes)
  ;
}

export type AppType = ReturnType<typeof _typedApp>;
