/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as shellAuthLayoutRouteImport } from './shell/auth/layout'
import { Route as shellAppLayoutRouteImport } from './shell/app-layout'
import { Route as chatDotchannelRoutingIdRouteImport } from './chat.$channelRoutingId'
import { Route as shellAuthSignupRouteImport } from './shell/auth/signup'
import { Route as shellAuthLoginRouteImport } from './shell/auth/login'
import { Route as DotDotModulesSystemPagesLayoutRouteImport } from './../modules/system/pages/layout'
import { Route as shellSettingsLayoutRouteImport } from './shell/settings/layout'
import { Route as DotDotModulesKnowledgeBasePagesLayoutRouteImport } from './../modules/knowledge-base/pages/layout'
import { Route as DotDotModulesConversationsPagesLayoutRouteImport } from './../modules/conversations/pages/layout'
import { Route as homeRouteImport } from './home'
import { Route as LogsRouteImport } from './../modules/system/pages/logs'
import { Route as ListRouteImport } from './../modules/system/pages/list'
import { Route as shellSettingsProfileRouteImport } from './shell/settings/profile'
import { Route as shellSettingsOrganizationRouteImport } from './shell/settings/organization'
import { Route as shellSettingsIntegrationsRouteImport } from './shell/settings/integrations'
import { Route as shellSettingsAppearanceRouteImport } from './shell/settings/appearance'
import { Route as shellSettingsApiKeysRouteImport } from './shell/settings/api-keys'
import { Route as SourcesRouteImport } from './../modules/knowledge-base/pages/sources'
import { Route as SearchRouteImport } from './../modules/knowledge-base/pages/search'
import { Route as DocumentsRouteImport } from './../modules/knowledge-base/pages/documents'
import { Route as ContactsIndexRouteImport } from './../modules/conversations/pages/contacts/index'
import { Route as ChannelsIndexRouteImport } from './../modules/conversations/pages/channels/index'
import { Route as SessionsOverviewRouteImport } from './../modules/conversations/pages/sessions/overview'
import { Route as SessionsConversationIdRouteImport } from './../modules/conversations/pages/sessions/$conversationId'
import { Route as ContactsContactIdRouteImport } from './../modules/conversations/pages/contacts/$contactId'
import { Route as AiMemoryRouteImport } from './../modules/conversations/pages/ai/memory'
import { Route as AiGuardrailsRouteImport } from './../modules/conversations/pages/ai/guardrails'
import { Route as AiEvalsRouteImport } from './../modules/conversations/pages/ai/evals'
import { Route as AiAgentsRouteImport } from './../modules/conversations/pages/ai/agents'

const shellAuthLayoutRoute = shellAuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const shellAppLayoutRoute = shellAppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const chatDotchannelRoutingIdRoute = chatDotchannelRoutingIdRouteImport.update({
  id: '/chat/$channelRoutingId',
  path: '/chat/$channelRoutingId',
  getParentRoute: () => rootRouteImport,
} as any)
const shellAuthSignupRoute = shellAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => shellAuthLayoutRoute,
} as any)
const shellAuthLoginRoute = shellAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => shellAuthLayoutRoute,
} as any)
const DotDotModulesSystemPagesLayoutRoute =
  DotDotModulesSystemPagesLayoutRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => shellAppLayoutRoute,
  } as any)
const shellSettingsLayoutRoute = shellSettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const DotDotModulesKnowledgeBasePagesLayoutRoute =
  DotDotModulesKnowledgeBasePagesLayoutRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => shellAppLayoutRoute,
  } as any)
const DotDotModulesConversationsPagesLayoutRoute =
  DotDotModulesConversationsPagesLayoutRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => shellAppLayoutRoute,
  } as any)
const homeRoute = homeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DotDotModulesSystemPagesLayoutRoute,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => DotDotModulesSystemPagesLayoutRoute,
} as any)
const shellSettingsProfileRoute = shellSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => shellSettingsLayoutRoute,
} as any)
const shellSettingsOrganizationRoute =
  shellSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => shellSettingsLayoutRoute,
  } as any)
const shellSettingsIntegrationsRoute =
  shellSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => shellSettingsLayoutRoute,
  } as any)
const shellSettingsAppearanceRoute = shellSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => shellSettingsLayoutRoute,
} as any)
const shellSettingsApiKeysRoute = shellSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => shellSettingsLayoutRoute,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DotDotModulesKnowledgeBasePagesLayoutRoute,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DotDotModulesKnowledgeBasePagesLayoutRoute,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DotDotModulesKnowledgeBasePagesLayoutRoute,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DotDotModulesConversationsPagesLayoutRoute,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => DotDotModulesConversationsPagesLayoutRoute,
} as any)
const SessionsOverviewRoute = SessionsOverviewRouteImport.update({
  id: '/sessions/overview',
  path: '/sessions/overview',
  getParentRoute: () => DotDotModulesConversationsPagesLayoutRoute,
} as any)
const SessionsConversationIdRoute = SessionsConversationIdRouteImport.update({
  id: '/sessions/$conversationId',
  path: '/sessions/$conversationId',
  getParentRoute: () => DotDotModulesConversationsPagesLayoutRoute,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => DotDotModulesConversationsPagesLayoutRoute,
} as any)
const AiMemoryRoute = AiMemoryRouteImport.update({
  id: '/ai/memory',
  path: '/ai/memory',
  getParentRoute: () => DotDotModulesConversationsPagesLayoutRoute,
} as any)
const AiGuardrailsRoute = AiGuardrailsRouteImport.update({
  id: '/ai/guardrails',
  path: '/ai/guardrails',
  getParentRoute: () => DotDotModulesConversationsPagesLayoutRoute,
} as any)
const AiEvalsRoute = AiEvalsRouteImport.update({
  id: '/ai/evals',
  path: '/ai/evals',
  getParentRoute: () => DotDotModulesConversationsPagesLayoutRoute,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/ai/agents',
  path: '/ai/agents',
  getParentRoute: () => DotDotModulesConversationsPagesLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeRoute
  '/conversations': typeof DotDotModulesConversationsPagesLayoutRouteWithChildren
  '/knowledge-base': typeof DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren
  '/settings': typeof shellSettingsLayoutRouteWithChildren
  '/system': typeof DotDotModulesSystemPagesLayoutRouteWithChildren
  '/login': typeof shellAuthLoginRoute
  '/signup': typeof shellAuthSignupRoute
  '/chat/$channelRoutingId': typeof chatDotchannelRoutingIdRoute
  '/knowledge-base/documents': typeof DocumentsRoute
  '/knowledge-base/search': typeof SearchRoute
  '/knowledge-base/sources': typeof SourcesRoute
  '/settings/api-keys': typeof shellSettingsApiKeysRoute
  '/settings/appearance': typeof shellSettingsAppearanceRoute
  '/settings/integrations': typeof shellSettingsIntegrationsRoute
  '/settings/organization': typeof shellSettingsOrganizationRoute
  '/settings/profile': typeof shellSettingsProfileRoute
  '/system/list': typeof ListRoute
  '/system/logs': typeof LogsRoute
  '/conversations/ai/agents': typeof AiAgentsRoute
  '/conversations/ai/evals': typeof AiEvalsRoute
  '/conversations/ai/guardrails': typeof AiGuardrailsRoute
  '/conversations/ai/memory': typeof AiMemoryRoute
  '/conversations/contacts/$contactId': typeof ContactsContactIdRoute
  '/conversations/sessions/$conversationId': typeof SessionsConversationIdRoute
  '/conversations/sessions/overview': typeof SessionsOverviewRoute
  '/conversations/channels/': typeof ChannelsIndexRoute
  '/conversations/contacts/': typeof ContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeRoute
  '/conversations': typeof DotDotModulesConversationsPagesLayoutRouteWithChildren
  '/knowledge-base': typeof DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren
  '/settings': typeof shellSettingsLayoutRouteWithChildren
  '/system': typeof DotDotModulesSystemPagesLayoutRouteWithChildren
  '/login': typeof shellAuthLoginRoute
  '/signup': typeof shellAuthSignupRoute
  '/chat/$channelRoutingId': typeof chatDotchannelRoutingIdRoute
  '/knowledge-base/documents': typeof DocumentsRoute
  '/knowledge-base/search': typeof SearchRoute
  '/knowledge-base/sources': typeof SourcesRoute
  '/settings/api-keys': typeof shellSettingsApiKeysRoute
  '/settings/appearance': typeof shellSettingsAppearanceRoute
  '/settings/integrations': typeof shellSettingsIntegrationsRoute
  '/settings/organization': typeof shellSettingsOrganizationRoute
  '/settings/profile': typeof shellSettingsProfileRoute
  '/system/list': typeof ListRoute
  '/system/logs': typeof LogsRoute
  '/conversations/ai/agents': typeof AiAgentsRoute
  '/conversations/ai/evals': typeof AiEvalsRoute
  '/conversations/ai/guardrails': typeof AiGuardrailsRoute
  '/conversations/ai/memory': typeof AiMemoryRoute
  '/conversations/contacts/$contactId': typeof ContactsContactIdRoute
  '/conversations/sessions/$conversationId': typeof SessionsConversationIdRoute
  '/conversations/sessions/overview': typeof SessionsOverviewRoute
  '/conversations/channels': typeof ChannelsIndexRoute
  '/conversations/contacts': typeof ContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof shellAppLayoutRouteWithChildren
  '/_auth': typeof shellAuthLayoutRouteWithChildren
  '/_app/': typeof homeRoute
  '/_app/conversations': typeof DotDotModulesConversationsPagesLayoutRouteWithChildren
  '/_app/knowledge-base': typeof DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren
  '/_app/settings': typeof shellSettingsLayoutRouteWithChildren
  '/_app/system': typeof DotDotModulesSystemPagesLayoutRouteWithChildren
  '/_auth/login': typeof shellAuthLoginRoute
  '/_auth/signup': typeof shellAuthSignupRoute
  '/chat/$channelRoutingId': typeof chatDotchannelRoutingIdRoute
  '/_app/knowledge-base/documents': typeof DocumentsRoute
  '/_app/knowledge-base/search': typeof SearchRoute
  '/_app/knowledge-base/sources': typeof SourcesRoute
  '/_app/settings/api-keys': typeof shellSettingsApiKeysRoute
  '/_app/settings/appearance': typeof shellSettingsAppearanceRoute
  '/_app/settings/integrations': typeof shellSettingsIntegrationsRoute
  '/_app/settings/organization': typeof shellSettingsOrganizationRoute
  '/_app/settings/profile': typeof shellSettingsProfileRoute
  '/_app/system/list': typeof ListRoute
  '/_app/system/logs': typeof LogsRoute
  '/_app/conversations/ai/agents': typeof AiAgentsRoute
  '/_app/conversations/ai/evals': typeof AiEvalsRoute
  '/_app/conversations/ai/guardrails': typeof AiGuardrailsRoute
  '/_app/conversations/ai/memory': typeof AiMemoryRoute
  '/_app/conversations/contacts/$contactId': typeof ContactsContactIdRoute
  '/_app/conversations/sessions/$conversationId': typeof SessionsConversationIdRoute
  '/_app/conversations/sessions/overview': typeof SessionsOverviewRoute
  '/_app/conversations/channels/': typeof ChannelsIndexRoute
  '/_app/conversations/contacts/': typeof ContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/knowledge-base'
    | '/settings'
    | '/system'
    | '/login'
    | '/signup'
    | '/chat/$channelRoutingId'
    | '/knowledge-base/documents'
    | '/knowledge-base/search'
    | '/knowledge-base/sources'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/organization'
    | '/settings/profile'
    | '/system/list'
    | '/system/logs'
    | '/conversations/ai/agents'
    | '/conversations/ai/evals'
    | '/conversations/ai/guardrails'
    | '/conversations/ai/memory'
    | '/conversations/contacts/$contactId'
    | '/conversations/sessions/$conversationId'
    | '/conversations/sessions/overview'
    | '/conversations/channels/'
    | '/conversations/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/knowledge-base'
    | '/settings'
    | '/system'
    | '/login'
    | '/signup'
    | '/chat/$channelRoutingId'
    | '/knowledge-base/documents'
    | '/knowledge-base/search'
    | '/knowledge-base/sources'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/organization'
    | '/settings/profile'
    | '/system/list'
    | '/system/logs'
    | '/conversations/ai/agents'
    | '/conversations/ai/evals'
    | '/conversations/ai/guardrails'
    | '/conversations/ai/memory'
    | '/conversations/contacts/$contactId'
    | '/conversations/sessions/$conversationId'
    | '/conversations/sessions/overview'
    | '/conversations/channels'
    | '/conversations/contacts'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/'
    | '/_app/conversations'
    | '/_app/knowledge-base'
    | '/_app/settings'
    | '/_app/system'
    | '/_auth/login'
    | '/_auth/signup'
    | '/chat/$channelRoutingId'
    | '/_app/knowledge-base/documents'
    | '/_app/knowledge-base/search'
    | '/_app/knowledge-base/sources'
    | '/_app/settings/api-keys'
    | '/_app/settings/appearance'
    | '/_app/settings/integrations'
    | '/_app/settings/organization'
    | '/_app/settings/profile'
    | '/_app/system/list'
    | '/_app/system/logs'
    | '/_app/conversations/ai/agents'
    | '/_app/conversations/ai/evals'
    | '/_app/conversations/ai/guardrails'
    | '/_app/conversations/ai/memory'
    | '/_app/conversations/contacts/$contactId'
    | '/_app/conversations/sessions/$conversationId'
    | '/_app/conversations/sessions/overview'
    | '/_app/conversations/channels/'
    | '/_app/conversations/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  shellAppLayoutRoute: typeof shellAppLayoutRouteWithChildren
  shellAuthLayoutRoute: typeof shellAuthLayoutRouteWithChildren
  chatDotchannelRoutingIdRoute: typeof chatDotchannelRoutingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof shellAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof shellAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$channelRoutingId': {
      id: '/chat/$channelRoutingId'
      path: '/chat/$channelRoutingId'
      fullPath: '/chat/$channelRoutingId'
      preLoaderRoute: typeof chatDotchannelRoutingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof shellAuthSignupRouteImport
      parentRoute: typeof shellAuthLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof shellAuthLoginRouteImport
      parentRoute: typeof shellAuthLayoutRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof DotDotModulesSystemPagesLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof shellSettingsLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof DotDotModulesConversationsPagesLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/system/logs': {
      id: '/_app/system/logs'
      path: '/logs'
      fullPath: '/system/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof DotDotModulesSystemPagesLayoutRoute
    }
    '/_app/system/list': {
      id: '/_app/system/list'
      path: '/list'
      fullPath: '/system/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof DotDotModulesSystemPagesLayoutRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof shellSettingsProfileRouteImport
      parentRoute: typeof shellSettingsLayoutRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof shellSettingsOrganizationRouteImport
      parentRoute: typeof shellSettingsLayoutRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof shellSettingsIntegrationsRouteImport
      parentRoute: typeof shellSettingsLayoutRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof shellSettingsAppearanceRouteImport
      parentRoute: typeof shellSettingsLayoutRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof shellSettingsApiKeysRouteImport
      parentRoute: typeof shellSettingsLayoutRoute
    }
    '/_app/knowledge-base/sources': {
      id: '/_app/knowledge-base/sources'
      path: '/sources'
      fullPath: '/knowledge-base/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRoute
    }
    '/_app/knowledge-base/search': {
      id: '/_app/knowledge-base/search'
      path: '/search'
      fullPath: '/knowledge-base/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRoute
    }
    '/_app/knowledge-base/documents': {
      id: '/_app/knowledge-base/documents'
      path: '/documents'
      fullPath: '/knowledge-base/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRoute
    }
    '/_app/conversations/contacts/': {
      id: '/_app/conversations/contacts/'
      path: '/contacts'
      fullPath: '/conversations/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof DotDotModulesConversationsPagesLayoutRoute
    }
    '/_app/conversations/channels/': {
      id: '/_app/conversations/channels/'
      path: '/channels'
      fullPath: '/conversations/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof DotDotModulesConversationsPagesLayoutRoute
    }
    '/_app/conversations/sessions/overview': {
      id: '/_app/conversations/sessions/overview'
      path: '/sessions/overview'
      fullPath: '/conversations/sessions/overview'
      preLoaderRoute: typeof SessionsOverviewRouteImport
      parentRoute: typeof DotDotModulesConversationsPagesLayoutRoute
    }
    '/_app/conversations/sessions/$conversationId': {
      id: '/_app/conversations/sessions/$conversationId'
      path: '/sessions/$conversationId'
      fullPath: '/conversations/sessions/$conversationId'
      preLoaderRoute: typeof SessionsConversationIdRouteImport
      parentRoute: typeof DotDotModulesConversationsPagesLayoutRoute
    }
    '/_app/conversations/contacts/$contactId': {
      id: '/_app/conversations/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/conversations/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof DotDotModulesConversationsPagesLayoutRoute
    }
    '/_app/conversations/ai/memory': {
      id: '/_app/conversations/ai/memory'
      path: '/ai/memory'
      fullPath: '/conversations/ai/memory'
      preLoaderRoute: typeof AiMemoryRouteImport
      parentRoute: typeof DotDotModulesConversationsPagesLayoutRoute
    }
    '/_app/conversations/ai/guardrails': {
      id: '/_app/conversations/ai/guardrails'
      path: '/ai/guardrails'
      fullPath: '/conversations/ai/guardrails'
      preLoaderRoute: typeof AiGuardrailsRouteImport
      parentRoute: typeof DotDotModulesConversationsPagesLayoutRoute
    }
    '/_app/conversations/ai/evals': {
      id: '/_app/conversations/ai/evals'
      path: '/ai/evals'
      fullPath: '/conversations/ai/evals'
      preLoaderRoute: typeof AiEvalsRouteImport
      parentRoute: typeof DotDotModulesConversationsPagesLayoutRoute
    }
    '/_app/conversations/ai/agents': {
      id: '/_app/conversations/ai/agents'
      path: '/ai/agents'
      fullPath: '/conversations/ai/agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof DotDotModulesConversationsPagesLayoutRoute
    }
  }
}

interface DotDotModulesConversationsPagesLayoutRouteChildren {
  AiAgentsRoute: typeof AiAgentsRoute
  AiEvalsRoute: typeof AiEvalsRoute
  AiGuardrailsRoute: typeof AiGuardrailsRoute
  AiMemoryRoute: typeof AiMemoryRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  SessionsConversationIdRoute: typeof SessionsConversationIdRoute
  SessionsOverviewRoute: typeof SessionsOverviewRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

const DotDotModulesConversationsPagesLayoutRouteChildren: DotDotModulesConversationsPagesLayoutRouteChildren =
  {
    AiAgentsRoute: AiAgentsRoute,
    AiEvalsRoute: AiEvalsRoute,
    AiGuardrailsRoute: AiGuardrailsRoute,
    AiMemoryRoute: AiMemoryRoute,
    ContactsContactIdRoute: ContactsContactIdRoute,
    SessionsConversationIdRoute: SessionsConversationIdRoute,
    SessionsOverviewRoute: SessionsOverviewRoute,
    ChannelsIndexRoute: ChannelsIndexRoute,
    ContactsIndexRoute: ContactsIndexRoute,
  }

const DotDotModulesConversationsPagesLayoutRouteWithChildren =
  DotDotModulesConversationsPagesLayoutRoute._addFileChildren(
    DotDotModulesConversationsPagesLayoutRouteChildren,
  )

interface DotDotModulesKnowledgeBasePagesLayoutRouteChildren {
  DocumentsRoute: typeof DocumentsRoute
  SearchRoute: typeof SearchRoute
  SourcesRoute: typeof SourcesRoute
}

const DotDotModulesKnowledgeBasePagesLayoutRouteChildren: DotDotModulesKnowledgeBasePagesLayoutRouteChildren =
  {
    DocumentsRoute: DocumentsRoute,
    SearchRoute: SearchRoute,
    SourcesRoute: SourcesRoute,
  }

const DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren =
  DotDotModulesKnowledgeBasePagesLayoutRoute._addFileChildren(
    DotDotModulesKnowledgeBasePagesLayoutRouteChildren,
  )

interface shellSettingsLayoutRouteChildren {
  shellSettingsApiKeysRoute: typeof shellSettingsApiKeysRoute
  shellSettingsAppearanceRoute: typeof shellSettingsAppearanceRoute
  shellSettingsIntegrationsRoute: typeof shellSettingsIntegrationsRoute
  shellSettingsOrganizationRoute: typeof shellSettingsOrganizationRoute
  shellSettingsProfileRoute: typeof shellSettingsProfileRoute
}

const shellSettingsLayoutRouteChildren: shellSettingsLayoutRouteChildren = {
  shellSettingsApiKeysRoute: shellSettingsApiKeysRoute,
  shellSettingsAppearanceRoute: shellSettingsAppearanceRoute,
  shellSettingsIntegrationsRoute: shellSettingsIntegrationsRoute,
  shellSettingsOrganizationRoute: shellSettingsOrganizationRoute,
  shellSettingsProfileRoute: shellSettingsProfileRoute,
}

const shellSettingsLayoutRouteWithChildren =
  shellSettingsLayoutRoute._addFileChildren(shellSettingsLayoutRouteChildren)

interface DotDotModulesSystemPagesLayoutRouteChildren {
  ListRoute: typeof ListRoute
  LogsRoute: typeof LogsRoute
}

const DotDotModulesSystemPagesLayoutRouteChildren: DotDotModulesSystemPagesLayoutRouteChildren =
  {
    ListRoute: ListRoute,
    LogsRoute: LogsRoute,
  }

const DotDotModulesSystemPagesLayoutRouteWithChildren =
  DotDotModulesSystemPagesLayoutRoute._addFileChildren(
    DotDotModulesSystemPagesLayoutRouteChildren,
  )

interface shellAppLayoutRouteChildren {
  homeRoute: typeof homeRoute
  DotDotModulesConversationsPagesLayoutRoute: typeof DotDotModulesConversationsPagesLayoutRouteWithChildren
  DotDotModulesKnowledgeBasePagesLayoutRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren
  shellSettingsLayoutRoute: typeof shellSettingsLayoutRouteWithChildren
  DotDotModulesSystemPagesLayoutRoute: typeof DotDotModulesSystemPagesLayoutRouteWithChildren
}

const shellAppLayoutRouteChildren: shellAppLayoutRouteChildren = {
  homeRoute: homeRoute,
  DotDotModulesConversationsPagesLayoutRoute:
    DotDotModulesConversationsPagesLayoutRouteWithChildren,
  DotDotModulesKnowledgeBasePagesLayoutRoute:
    DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren,
  shellSettingsLayoutRoute: shellSettingsLayoutRouteWithChildren,
  DotDotModulesSystemPagesLayoutRoute:
    DotDotModulesSystemPagesLayoutRouteWithChildren,
}

const shellAppLayoutRouteWithChildren = shellAppLayoutRoute._addFileChildren(
  shellAppLayoutRouteChildren,
)

interface shellAuthLayoutRouteChildren {
  shellAuthLoginRoute: typeof shellAuthLoginRoute
  shellAuthSignupRoute: typeof shellAuthSignupRoute
}

const shellAuthLayoutRouteChildren: shellAuthLayoutRouteChildren = {
  shellAuthLoginRoute: shellAuthLoginRoute,
  shellAuthSignupRoute: shellAuthSignupRoute,
}

const shellAuthLayoutRouteWithChildren = shellAuthLayoutRoute._addFileChildren(
  shellAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  shellAppLayoutRoute: shellAppLayoutRouteWithChildren,
  shellAuthLayoutRoute: shellAuthLayoutRouteWithChildren,
  chatDotchannelRoutingIdRoute: chatDotchannelRoutingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
