/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as shellAuthLayoutRouteImport } from './shell/auth/layout'
import { Route as shellAppLayoutRouteImport } from './shell/app-layout'
import { Route as shellAuthSignupRouteImport } from './shell/auth/signup'
import { Route as shellAuthLoginRouteImport } from './shell/auth/login'
import { Route as DotDotModulesSystemPagesLayoutRouteImport } from './../modules/system/pages/layout'
import { Route as shellSettingsLayoutRouteImport } from './shell/settings/layout'
import { Route as DotDotModulesKnowledgeBasePagesLayoutRouteImport } from './../modules/knowledge-base/pages/layout'
import { Route as DotDotModulesChatbotPagesLayoutRouteImport } from './../modules/chatbot/pages/layout'
import { Route as homeRouteImport } from './home'
import { Route as LogsRouteImport } from './../modules/system/pages/logs'
import { Route as ListRouteImport } from './../modules/system/pages/list'
import { Route as shellSettingsProfileRouteImport } from './shell/settings/profile'
import { Route as shellSettingsOrganizationRouteImport } from './shell/settings/organization'
import { Route as shellSettingsAppearanceRouteImport } from './shell/settings/appearance'
import { Route as shellSettingsApiKeysRouteImport } from './shell/settings/api-keys'
import { Route as SourcesRouteImport } from './../modules/knowledge-base/pages/sources'
import { Route as SearchRouteImport } from './../modules/knowledge-base/pages/search'
import { Route as DocumentsRouteImport } from './../modules/knowledge-base/pages/documents'
import { Route as ThreadsRouteImport } from './../modules/chatbot/pages/threads'
import { Route as AssistantsRouteImport } from './../modules/chatbot/pages/assistants'

const shellAuthLayoutRoute = shellAuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const shellAppLayoutRoute = shellAppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const shellAuthSignupRoute = shellAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => shellAuthLayoutRoute,
} as any)
const shellAuthLoginRoute = shellAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => shellAuthLayoutRoute,
} as any)
const DotDotModulesSystemPagesLayoutRoute =
  DotDotModulesSystemPagesLayoutRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => shellAppLayoutRoute,
  } as any)
const shellSettingsLayoutRoute = shellSettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const DotDotModulesKnowledgeBasePagesLayoutRoute =
  DotDotModulesKnowledgeBasePagesLayoutRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => shellAppLayoutRoute,
  } as any)
const DotDotModulesChatbotPagesLayoutRoute =
  DotDotModulesChatbotPagesLayoutRouteImport.update({
    id: '/chatbot',
    path: '/chatbot',
    getParentRoute: () => shellAppLayoutRoute,
  } as any)
const homeRoute = homeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DotDotModulesSystemPagesLayoutRoute,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => DotDotModulesSystemPagesLayoutRoute,
} as any)
const shellSettingsProfileRoute = shellSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => shellSettingsLayoutRoute,
} as any)
const shellSettingsOrganizationRoute =
  shellSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => shellSettingsLayoutRoute,
  } as any)
const shellSettingsAppearanceRoute = shellSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => shellSettingsLayoutRoute,
} as any)
const shellSettingsApiKeysRoute = shellSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => shellSettingsLayoutRoute,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DotDotModulesKnowledgeBasePagesLayoutRoute,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DotDotModulesKnowledgeBasePagesLayoutRoute,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DotDotModulesKnowledgeBasePagesLayoutRoute,
} as any)
const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => DotDotModulesChatbotPagesLayoutRoute,
} as any)
const AssistantsRoute = AssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => DotDotModulesChatbotPagesLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeRoute
  '/chatbot': typeof DotDotModulesChatbotPagesLayoutRouteWithChildren
  '/knowledge-base': typeof DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren
  '/settings': typeof shellSettingsLayoutRouteWithChildren
  '/system': typeof DotDotModulesSystemPagesLayoutRouteWithChildren
  '/login': typeof shellAuthLoginRoute
  '/signup': typeof shellAuthSignupRoute
  '/chatbot/assistants': typeof AssistantsRoute
  '/chatbot/threads': typeof ThreadsRoute
  '/knowledge-base/documents': typeof DocumentsRoute
  '/knowledge-base/search': typeof SearchRoute
  '/knowledge-base/sources': typeof SourcesRoute
  '/settings/api-keys': typeof shellSettingsApiKeysRoute
  '/settings/appearance': typeof shellSettingsAppearanceRoute
  '/settings/organization': typeof shellSettingsOrganizationRoute
  '/settings/profile': typeof shellSettingsProfileRoute
  '/system/list': typeof ListRoute
  '/system/logs': typeof LogsRoute
}
export interface FileRoutesByTo {
  '/': typeof homeRoute
  '/chatbot': typeof DotDotModulesChatbotPagesLayoutRouteWithChildren
  '/knowledge-base': typeof DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren
  '/settings': typeof shellSettingsLayoutRouteWithChildren
  '/system': typeof DotDotModulesSystemPagesLayoutRouteWithChildren
  '/login': typeof shellAuthLoginRoute
  '/signup': typeof shellAuthSignupRoute
  '/chatbot/assistants': typeof AssistantsRoute
  '/chatbot/threads': typeof ThreadsRoute
  '/knowledge-base/documents': typeof DocumentsRoute
  '/knowledge-base/search': typeof SearchRoute
  '/knowledge-base/sources': typeof SourcesRoute
  '/settings/api-keys': typeof shellSettingsApiKeysRoute
  '/settings/appearance': typeof shellSettingsAppearanceRoute
  '/settings/organization': typeof shellSettingsOrganizationRoute
  '/settings/profile': typeof shellSettingsProfileRoute
  '/system/list': typeof ListRoute
  '/system/logs': typeof LogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof shellAppLayoutRouteWithChildren
  '/_auth': typeof shellAuthLayoutRouteWithChildren
  '/_app/': typeof homeRoute
  '/_app/chatbot': typeof DotDotModulesChatbotPagesLayoutRouteWithChildren
  '/_app/knowledge-base': typeof DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren
  '/_app/settings': typeof shellSettingsLayoutRouteWithChildren
  '/_app/system': typeof DotDotModulesSystemPagesLayoutRouteWithChildren
  '/_auth/login': typeof shellAuthLoginRoute
  '/_auth/signup': typeof shellAuthSignupRoute
  '/_app/chatbot/assistants': typeof AssistantsRoute
  '/_app/chatbot/threads': typeof ThreadsRoute
  '/_app/knowledge-base/documents': typeof DocumentsRoute
  '/_app/knowledge-base/search': typeof SearchRoute
  '/_app/knowledge-base/sources': typeof SourcesRoute
  '/_app/settings/api-keys': typeof shellSettingsApiKeysRoute
  '/_app/settings/appearance': typeof shellSettingsAppearanceRoute
  '/_app/settings/organization': typeof shellSettingsOrganizationRoute
  '/_app/settings/profile': typeof shellSettingsProfileRoute
  '/_app/system/list': typeof ListRoute
  '/_app/system/logs': typeof LogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chatbot'
    | '/knowledge-base'
    | '/settings'
    | '/system'
    | '/login'
    | '/signup'
    | '/chatbot/assistants'
    | '/chatbot/threads'
    | '/knowledge-base/documents'
    | '/knowledge-base/search'
    | '/knowledge-base/sources'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/organization'
    | '/settings/profile'
    | '/system/list'
    | '/system/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatbot'
    | '/knowledge-base'
    | '/settings'
    | '/system'
    | '/login'
    | '/signup'
    | '/chatbot/assistants'
    | '/chatbot/threads'
    | '/knowledge-base/documents'
    | '/knowledge-base/search'
    | '/knowledge-base/sources'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/organization'
    | '/settings/profile'
    | '/system/list'
    | '/system/logs'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/'
    | '/_app/chatbot'
    | '/_app/knowledge-base'
    | '/_app/settings'
    | '/_app/system'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/chatbot/assistants'
    | '/_app/chatbot/threads'
    | '/_app/knowledge-base/documents'
    | '/_app/knowledge-base/search'
    | '/_app/knowledge-base/sources'
    | '/_app/settings/api-keys'
    | '/_app/settings/appearance'
    | '/_app/settings/organization'
    | '/_app/settings/profile'
    | '/_app/system/list'
    | '/_app/system/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  shellAppLayoutRoute: typeof shellAppLayoutRouteWithChildren
  shellAuthLayoutRoute: typeof shellAuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof shellAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof shellAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof shellAuthSignupRouteImport
      parentRoute: typeof shellAuthLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof shellAuthLoginRouteImport
      parentRoute: typeof shellAuthLayoutRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof DotDotModulesSystemPagesLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof shellSettingsLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/chatbot': {
      id: '/_app/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof DotDotModulesChatbotPagesLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/system/logs': {
      id: '/_app/system/logs'
      path: '/logs'
      fullPath: '/system/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof DotDotModulesSystemPagesLayoutRoute
    }
    '/_app/system/list': {
      id: '/_app/system/list'
      path: '/list'
      fullPath: '/system/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof DotDotModulesSystemPagesLayoutRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof shellSettingsProfileRouteImport
      parentRoute: typeof shellSettingsLayoutRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof shellSettingsOrganizationRouteImport
      parentRoute: typeof shellSettingsLayoutRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof shellSettingsAppearanceRouteImport
      parentRoute: typeof shellSettingsLayoutRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof shellSettingsApiKeysRouteImport
      parentRoute: typeof shellSettingsLayoutRoute
    }
    '/_app/knowledge-base/sources': {
      id: '/_app/knowledge-base/sources'
      path: '/sources'
      fullPath: '/knowledge-base/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRoute
    }
    '/_app/knowledge-base/search': {
      id: '/_app/knowledge-base/search'
      path: '/search'
      fullPath: '/knowledge-base/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRoute
    }
    '/_app/knowledge-base/documents': {
      id: '/_app/knowledge-base/documents'
      path: '/documents'
      fullPath: '/knowledge-base/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRoute
    }
    '/_app/chatbot/threads': {
      id: '/_app/chatbot/threads'
      path: '/threads'
      fullPath: '/chatbot/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof DotDotModulesChatbotPagesLayoutRoute
    }
    '/_app/chatbot/assistants': {
      id: '/_app/chatbot/assistants'
      path: '/assistants'
      fullPath: '/chatbot/assistants'
      preLoaderRoute: typeof AssistantsRouteImport
      parentRoute: typeof DotDotModulesChatbotPagesLayoutRoute
    }
  }
}

interface DotDotModulesChatbotPagesLayoutRouteChildren {
  AssistantsRoute: typeof AssistantsRoute
  ThreadsRoute: typeof ThreadsRoute
}

const DotDotModulesChatbotPagesLayoutRouteChildren: DotDotModulesChatbotPagesLayoutRouteChildren =
  {
    AssistantsRoute: AssistantsRoute,
    ThreadsRoute: ThreadsRoute,
  }

const DotDotModulesChatbotPagesLayoutRouteWithChildren =
  DotDotModulesChatbotPagesLayoutRoute._addFileChildren(
    DotDotModulesChatbotPagesLayoutRouteChildren,
  )

interface DotDotModulesKnowledgeBasePagesLayoutRouteChildren {
  DocumentsRoute: typeof DocumentsRoute
  SearchRoute: typeof SearchRoute
  SourcesRoute: typeof SourcesRoute
}

const DotDotModulesKnowledgeBasePagesLayoutRouteChildren: DotDotModulesKnowledgeBasePagesLayoutRouteChildren =
  {
    DocumentsRoute: DocumentsRoute,
    SearchRoute: SearchRoute,
    SourcesRoute: SourcesRoute,
  }

const DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren =
  DotDotModulesKnowledgeBasePagesLayoutRoute._addFileChildren(
    DotDotModulesKnowledgeBasePagesLayoutRouteChildren,
  )

interface shellSettingsLayoutRouteChildren {
  shellSettingsApiKeysRoute: typeof shellSettingsApiKeysRoute
  shellSettingsAppearanceRoute: typeof shellSettingsAppearanceRoute
  shellSettingsOrganizationRoute: typeof shellSettingsOrganizationRoute
  shellSettingsProfileRoute: typeof shellSettingsProfileRoute
}

const shellSettingsLayoutRouteChildren: shellSettingsLayoutRouteChildren = {
  shellSettingsApiKeysRoute: shellSettingsApiKeysRoute,
  shellSettingsAppearanceRoute: shellSettingsAppearanceRoute,
  shellSettingsOrganizationRoute: shellSettingsOrganizationRoute,
  shellSettingsProfileRoute: shellSettingsProfileRoute,
}

const shellSettingsLayoutRouteWithChildren =
  shellSettingsLayoutRoute._addFileChildren(shellSettingsLayoutRouteChildren)

interface DotDotModulesSystemPagesLayoutRouteChildren {
  ListRoute: typeof ListRoute
  LogsRoute: typeof LogsRoute
}

const DotDotModulesSystemPagesLayoutRouteChildren: DotDotModulesSystemPagesLayoutRouteChildren =
  {
    ListRoute: ListRoute,
    LogsRoute: LogsRoute,
  }

const DotDotModulesSystemPagesLayoutRouteWithChildren =
  DotDotModulesSystemPagesLayoutRoute._addFileChildren(
    DotDotModulesSystemPagesLayoutRouteChildren,
  )

interface shellAppLayoutRouteChildren {
  homeRoute: typeof homeRoute
  DotDotModulesChatbotPagesLayoutRoute: typeof DotDotModulesChatbotPagesLayoutRouteWithChildren
  DotDotModulesKnowledgeBasePagesLayoutRoute: typeof DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren
  shellSettingsLayoutRoute: typeof shellSettingsLayoutRouteWithChildren
  DotDotModulesSystemPagesLayoutRoute: typeof DotDotModulesSystemPagesLayoutRouteWithChildren
}

const shellAppLayoutRouteChildren: shellAppLayoutRouteChildren = {
  homeRoute: homeRoute,
  DotDotModulesChatbotPagesLayoutRoute:
    DotDotModulesChatbotPagesLayoutRouteWithChildren,
  DotDotModulesKnowledgeBasePagesLayoutRoute:
    DotDotModulesKnowledgeBasePagesLayoutRouteWithChildren,
  shellSettingsLayoutRoute: shellSettingsLayoutRouteWithChildren,
  DotDotModulesSystemPagesLayoutRoute:
    DotDotModulesSystemPagesLayoutRouteWithChildren,
}

const shellAppLayoutRouteWithChildren = shellAppLayoutRoute._addFileChildren(
  shellAppLayoutRouteChildren,
)

interface shellAuthLayoutRouteChildren {
  shellAuthLoginRoute: typeof shellAuthLoginRoute
  shellAuthSignupRoute: typeof shellAuthSignupRoute
}

const shellAuthLayoutRouteChildren: shellAuthLayoutRouteChildren = {
  shellAuthLoginRoute: shellAuthLoginRoute,
  shellAuthSignupRoute: shellAuthSignupRoute,
}

const shellAuthLayoutRouteWithChildren = shellAuthLayoutRoute._addFileChildren(
  shellAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  shellAppLayoutRoute: shellAppLayoutRouteWithChildren,
  shellAuthLayoutRoute: shellAuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
