// @generated by scripts/gen-auth-schema.ts — do not edit by hand.
// Run `bun run gen:auth` to regenerate from auth/auth.config.ts.

export * from './schema-tables'
// Auth-prefixed aliases — vobase code refers to these tables as authUser, authSession, …
export {
  account as authAccount,
  apikey as authApikey,
  invitation as authInvitation,
  member as authMember,
  organization as authOrganization,
  session as authSession,
  team as authTeam,
  teamMember as authTeamMember,
  user as authUser,
  verification as authVerification,
} from './schema-tables'
