/**
 * Bake current.sql fixtures into a numbered Drizzle migration, then reset current.sql.
 *
 * Usage: bun run db:commit
 */
import { $ } from 'bun';

import { processSqlFile } from './utils/process-sql-file';

const output = await $`bun run drizzle-kit generate --custom`.text();
const filenameMatch = output.match(/\S*\/\d+_\w+\.sql/);

if (!filenameMatch) {
  console.error('[db:commit] No SQL file generated by drizzle-kit');
  console.error(output);
  process.exit(1);
}

const filename = filenameMatch[0];
const currentSqlPath = `${import.meta.dir}/../db/current.sql`;
const currentSql = await processSqlFile(currentSqlPath);

await Bun.write(filename, currentSql);
console.log(`[db:commit] Fixtures committed to ${filename}`);

const resetTemplate = `-- Fixtures entry point
-- Use --!include to include SQL files with glob support
-- Run \`bun run db:current\` to apply during development
-- Run \`bun run db:commit\` to bake into a migration

-- Extensions
--!include extensions/*.sql

-- Functions
--!include fixtures/functions/*.sql

-- Triggers
--!include fixtures/triggers/*.sql
`;

await Bun.write(currentSqlPath, resetTemplate);
console.log('[db:commit] current.sql reset to template');
