#!/usr/bin/env bun
/**
 * gen:auth — regenerate the auth drizzle schema from the better-auth CLI.
 *
 * Produces two GENERATED files (never edit either by hand):
 *   - `auth/schema-tables.ts` — the `authPgSchema.table(...)` definitions with
 *     better-auth's native export names (`user`, `session`, …). This is the
 *     file `drizzle.config.ts` points at, so each table is seen exactly once.
 *   - `auth/schema.ts` — re-exports everything from `schema-tables.ts` plus
 *     `auth`-prefixed aliases (`authUser`, `authSession`, …). App code imports
 *     from `@auth/schema`; drizzle-kit never sees the aliases (which would
 *     otherwise register every table twice).
 *
 * Pipeline:
 *   1. The better-auth CLI (`bunx auth`, the pinned `auth` devDependency)
 *      introspects `auth/auth.config.ts` and emits a flat drizzle schema
 *      (bare `pgTable(...)`, public Postgres schema).
 *   2. `transformAuthSchema` rewrites it into the `auth` pg schema, applies the
 *      vobase timestamp conventions, and derives the alias block.
 *   3. biome formats both files.
 *
 * To change the auth tables, edit the plugin set in `auth/plugins.ts` and
 * rerun `bun run gen:auth`. CI guards this via `bun run check:auth-schema`.
 */

import { existsSync } from 'node:fs'
import { mkdir, rm } from 'node:fs/promises'

const TEMPLATE_ROOT = `${import.meta.dir}/..`
const GEN_DIR = `${TEMPLATE_ROOT}/.auth-gen`
const RAW_FILE = `${GEN_DIR}/schema.ts`
const TABLES_FILE = `${TEMPLATE_ROOT}/auth/schema-tables.ts`
const SCHEMA_FILE = `${TEMPLATE_ROOT}/auth/schema.ts`

const BANNER =
  '// @generated by scripts/gen-auth-schema.ts — do not edit by hand.\n' +
  '// Run `bun run gen:auth` to regenerate from auth/auth.config.ts.\n\n'

export interface GeneratedAuthSchema {
  /** `auth/schema-tables.ts` — native-named table definitions (drizzle-kit reads this). */
  tables: string
  /** `auth/schema.ts` — re-export + `auth`-prefixed aliases (app code reads this). */
  schema: string
}

/**
 * Rewrite the better-auth CLI's flat drizzle output into the vobase shape.
 * Pure + deterministic so `check:auth-schema` can diff it against the
 * committed files.
 */
export function transformAuthSchema(raw: string): GeneratedAuthSchema {
  let out = raw

  // 1. Strip drizzle `relations()` — drizzle 1.0 dropped the v0-style helper
  //    in favour of `defineRelations`, and vobase doesn't use either. The CLI
  //    emits them at the end of the file, after every table.
  out = out.replace(/\n+export const \w+Relations = relations\([\s\S]*$/, '\n')
  out = out.replace(/^import \{ relations \} from ["']drizzle-orm["'];?\n/m, '')

  // 2. Call sites: `pgTable(` → `authPgSchema.table(`.
  out = out.replace(/\bpgTable\(/g, 'authPgSchema.table(')

  // 3. Drop the now-unused `pgTable` from the drizzle-orm import and inject the
  //    `authPgSchema` import.
  out = out.replace(/import\s*\{([^}]*)\}\s*from\s*["']drizzle-orm\/pg-core["'];?/, (_match, names: string) => {
    const kept = names
      .split(',')
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && s !== 'pgTable')
    return `import { ${kept.join(', ')} } from 'drizzle-orm/pg-core'\n\nimport { authPgSchema } from './pg-schema'`
  })

  // 4. vobase convention: every timestamp column is timezone-aware.
  out = out.replace(/\btimestamp\((["'][^"']+["'])\)/g, 'timestamp($1, { withTimezone: true })')

  // 5. vobase convention: `created_at` / `updated_at` default to `now()` at the
  //    DB layer. better-auth always sets them in app code so it omits the
  //    default, but vobase code also inserts these rows directly (seeds,
  //    auto-enroll), so the column default must exist. The negative lookahead
  //    tolerates whitespace because the CLI emits multi-line chains
  //    (`timestamp(...)\n  .defaultNow()`) for columns that also carry
  //    `.$onUpdate()` — without `\s*` we'd append a second `.defaultNow()`.
  out = out.replace(
    /\btimestamp\((["'](?:created_at|updated_at)["']), \{ withTimezone: true \}\)(?!\s*\.defaultNow\(\))/g,
    'timestamp($1, { withTimezone: true }).defaultNow()',
  )

  // 6. Derive the `auth`-prefixed alias block so vobase code keeps referring to
  //    `authUser`, `authSession`, … rather than better-auth's bare names.
  const tableNames = [...out.matchAll(/^export const (\w+) = authPgSchema\.table\(/gm)].map((m) => m[1])
  if (tableNames.length === 0) throw new Error('gen:auth — no tables found in CLI output; aborting')
  const aliasLines = tableNames
    .map((name) => `  ${name} as auth${name.charAt(0).toUpperCase()}${name.slice(1)},`)
    .join('\n')

  const tables = `${BANNER}${out.trimEnd()}\n`
  const schema =
    `${BANNER}export * from './schema-tables'\n\n` +
    '// Auth-prefixed aliases — vobase code refers to these tables as authUser, authSession, …\n' +
    `export {\n${aliasLines}\n} from './schema-tables'\n`

  return { tables, schema }
}

/** Run the CLI + transform, returning both file contents (does not write). */
export async function generateAuthSchema(): Promise<GeneratedAuthSchema> {
  await rm(GEN_DIR, { recursive: true, force: true })
  await mkdir(GEN_DIR, { recursive: true })

  // `bunx auth` (no `@latest`) resolves the pinned `auth` devDependency, so the
  // generated schema — and `check:auth-schema` — track the lockfile rather than
  // whatever the registry's `latest` tag points at on any given CI run.
  const cli = Bun.spawnSync(
    ['bunx', 'auth', 'generate', '--config', 'auth/auth.config.ts', '--output', '.auth-gen/schema.ts', '--yes'],
    { cwd: TEMPLATE_ROOT, stdio: ['inherit', 'inherit', 'inherit'] },
  )
  if (cli.exitCode !== 0) throw new Error('gen:auth — better-auth CLI `generate` failed')
  if (!existsSync(RAW_FILE)) throw new Error(`gen:auth — expected CLI output at ${RAW_FILE}`)

  const raw = await Bun.file(RAW_FILE).text()
  const result = transformAuthSchema(raw)

  await rm(GEN_DIR, { recursive: true, force: true })
  return result
}

if (import.meta.main) {
  const { tables, schema } = await generateAuthSchema()
  await Bun.write(TABLES_FILE, tables)
  await Bun.write(SCHEMA_FILE, schema)

  const fmt = Bun.spawnSync(['bunx', 'biome', 'check', '--write', 'auth/schema-tables.ts', 'auth/schema.ts'], {
    cwd: TEMPLATE_ROOT,
    stdio: ['inherit', 'inherit', 'inherit'],
  })
  if (fmt.exitCode !== 0) throw new Error('gen:auth — biome formatting of generated files failed')

  process.stdout.write('✓ auth/schema-tables.ts + auth/schema.ts regenerated\n')
}
