/**
 * Route generation script for vobase projects.
 *
 * Scans modules/ for directories containing pages/ subdirectories,
 * then generates src/routes.ts with TanStack virtual file routes.
 *
 * Usage: bun run scripts/generate.ts
 */
import { exists, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

const MODULE_NAME_PATTERN = /^[a-z0-9-]+$/;

async function listModuleDirs(modulesDir: string): Promise<string[]> {
  if (!(await exists(modulesDir))) return [];

  const entries = new Bun.Glob('*').scanSync({
    cwd: modulesDir,
    onlyFiles: false,
  });
  return [...entries].filter((name) => MODULE_NAME_PATTERN.test(name)).sort();
}

async function findModulesWithPages(projectRoot: string): Promise<string[]> {
  const modulesDir = join(projectRoot, 'modules');
  const modules = await listModuleDirs(modulesDir);

  const results: string[] = [];
  for (const name of modules) {
    if (await exists(join(modulesDir, name, 'pages'))) {
      results.push(name);
    }
  }
  return results;
}

// Modules whose pages are registered as flat individual routes rather than
// using physical() scanning. These are listed explicitly in buildRoutesSource.
const FLAT_ROUTE_MODULES = new Set(['ai']);

function buildModuleRoute(moduleName: string): string {
  return [
    `    route('/${moduleName}', '../modules/${moduleName}/pages/layout.tsx', [`,
    `      physical('../modules/${moduleName}/pages/'),`,
    '    ]),',
  ].join('\n');
}

function buildAiRoutes(): string[] {
  return [
    "    route('/conversations', '../modules/ai/pages/conversations/index.tsx', [",
    '      route(',
    "        '/$conversationId',",
    "        '../modules/ai/pages/conversations/$conversationId.tsx',",
    '      ),',
    '    ]),',
    "    route('/contacts', '../modules/ai/pages/contacts/index.tsx'),",
    '    route(',
    "      '/contacts/$contactId',",
    "      '../modules/ai/pages/contacts/$contactId.tsx',",
    '    ),',
    "    route('/channels', '../modules/ai/pages/channels/index.tsx'),",
    "    layout('ai', '../modules/ai/pages/ai/layout.tsx', [",
    "      route('/ai/agents', '../modules/ai/pages/ai/agents.tsx'),",
    "      route('/ai/evals', '../modules/ai/pages/ai/evals.tsx'),",
    "      route('/ai/guardrails', '../modules/ai/pages/ai/guardrails.tsx'),",
    "      route('/ai/memory', '../modules/ai/pages/ai/memory.tsx'),",
    '    ]),',
  ];
}

function buildRoutesSource(moduleNames: string[]): string {
  const sortedModuleNames = [...moduleNames].sort((left, right) =>
    left.localeCompare(right),
  );
  const settingsRoutes = [
    "    route('/settings', 'shell/settings/layout.tsx', [",
    "      route('/profile', 'shell/settings/profile.tsx'),",
    "      route('/account', 'shell/settings/account.tsx'),",
    "      route('/appearance', 'shell/settings/appearance.tsx'),",
    "      route('/notifications', 'shell/settings/notifications.tsx'),",
    "      route('/display', 'shell/settings/display.tsx'),",
    "      route('/api-keys', 'shell/settings/api-keys.tsx'),",
    "      route('/integrations', 'shell/settings/integrations.tsx'),",
    "      route('/organization', 'shell/settings/organization.tsx'),",
    '    ]),',
  ];

  const moduleRoutes = sortedModuleNames.flatMap((name) => {
    if (FLAT_ROUTE_MODULES.has(name)) return buildAiRoutes();
    return [buildModuleRoute(name)];
  });

  const appChildren = [
    "    route('/', 'home.tsx'),",
    ...moduleRoutes,
    ...settingsRoutes,
  ];

  return [
    'import {',
    '  layout,',
    '  physical,',
    '  rootRoute,',
    '  route,',
    "} from '@tanstack/virtual-file-routes';",
    '',
    "export const routes = rootRoute('root.tsx', [",
    "  route('/chat/$channelRoutingId', 'chat.$channelRoutingId.tsx'),",
    "  layout('auth', 'shell/auth/layout.tsx', [",
    "    route('/login', 'shell/auth/login.tsx'),",
    "    route('/signup', 'shell/auth/signup.tsx'),",
    '  ]),',
    "  layout('app', 'shell/app-layout.tsx', [",
    ...appChildren,
    '  ]),',
    ']);',
    '',
  ].join('\n');
}

function buildApiTypesSource(moduleNames: string[]): string {
  const imports = moduleNames.map((name) => {
    const camelName = `${name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}Module`;
    return `import { ${camelName} } from '../modules/${name}';`;
  });

  const chains = moduleNames.map((name) => {
    const camelName = `${name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}Module`;
    return `    .route('/api/${name}', ${camelName}.routes)`;
  });

  return [
    '// This file is auto-generated by scripts/generate.ts',
    '// Do not edit manually.',
    "import { Hono } from 'hono';",
    '',
    ...imports,
    '',
    "// Type-only chain — mirrors createApp() route mounting but preserves Hono's literal types.",
    '// This function is never called at runtime.',
    'function _typedApp() {',
    '  return new Hono()',
    "    .get('/health', (c) => c.json({ status: 'ok' as const, uptime: 0 }))",
    ...chains,
    '  ;',
    '}',
    '',
    'export type AppType = ReturnType<typeof _typedApp>;',
    '',
  ].join('\n');
}

async function checkNavigationCoverage(
  cwd: string,
  modulesWithPages: string[],
): Promise<void> {
  if (modulesWithPages.length === 0) return;

  const navPath = join(cwd, 'src', 'constants', 'navigation.ts');
  if (!(await exists(navPath))) return;

  const navSource = await Bun.file(navPath).text();
  for (const name of modulesWithPages) {
    const pattern = new RegExp(`\\b${name}\\b`);
    if (!pattern.test(navSource)) {
      console.warn(
        `\u26a0 Module "${name}" has pages/ but no navigation entry in src/constants/navigation.ts`,
      );
    }
  }
}

async function main() {
  const cwd = process.cwd();

  // 1. Generate route tree (modules with pages/)
  const modulesWithPages = await findModulesWithPages(cwd);
  const routesPath = join(cwd, 'src', 'routes.ts');
  await mkdir(join(cwd, 'src'), { recursive: true });
  await Bun.write(routesPath, buildRoutesSource(modulesWithPages));
  console.log(
    `Generated src/routes.ts with modules: ${modulesWithPages.join(', ') || '(none)'}`,
  );

  // 2. Generate typed API client (modules with index.ts = proper defineModule exports)
  const modulesDir = join(cwd, 'modules');
  const allDirs = await listModuleDirs(modulesDir);
  const allModules: string[] = [];
  for (const name of allDirs) {
    if (await exists(join(modulesDir, name, 'index.ts'))) {
      allModules.push(name);
    }
  }
  const apiTypesPath = join(cwd, 'src', 'api-types.generated.ts');
  await Bun.write(apiTypesPath, buildApiTypesSource(allModules));
  console.log(
    `Generated src/api-types.generated.ts with modules: ${allModules.join(', ') || '(none)'}`,
  );

  // 3. Warn about modules with pages but no navigation entry
  await checkNavigationCoverage(cwd, modulesWithPages);
}

main().catch((error) => {
  console.error('Generate failed:', error);
  process.exit(1);
});
