/**
 * Placeholder agent id for the system-owned pending-decision-followup cron.
 *
 * US-013 dispatcher will resolve this string to a real agent (either by
 * seeding a system agent named `pending-decision-followup-agent` or by
 * special-casing the literal in the wake builder). For US-010 it only needs
 * to be a stable, identifiable string — the dispatcher is still a stub that
 * throws, so the cron never fires.
 */
export const PENDING_DECISION_FOLLOWUP_AGENT_ID = 'agent:pending-decision-followup-system'

/**
 * Stable rule name + cron expression for the pending-decision-followup sweep.
 * Exported so tests can target the seeded row by name.
 */
export const PENDING_DECISION_FOLLOWUP_RULE_NAME = 'pending-decision-followup'
export const PENDING_DECISION_FOLLOWUP_CRON = '*/10 * * * *' // every 10 minutes

/**
 * Seeds `automations.automations` from `automations.automation_rules`,
 * then seeds the system-owned `pending-decision-followup` cron row.
 *
 * For every cron schedule row, inserts a paired automations row with
 * `eventName='cron'` and `action={type:'wake', agentId, lane:'standalone'}`.
 * Idempotent via ON CONFLICT (organization_id, name) DO NOTHING.
 *
 * Runs after `seedAgents` (which populates `automation_rules`) so the agent
 * FK is always satisfied.
 *
 * The pending-decision-followup row uses a placeholder `agentId` string;
 * US-013's dispatcher resolves it before scheduling a wake.
 */
export async function seedAutomations(db: unknown, opts?: { organizationId?: string }): Promise<void> {
  // biome-ignore lint/plugin/no-dynamic-import: seeds load schema lazily to avoid module-init-order issues (convention across modules/*/seed.ts)
  const { automations, automationRules } = await import('@modules/automations/schema')

  // Using raw drizzle select + insert to build the mirror rows from
  // automation_rules without requiring a raw SQL client in the seed.
  const d = db as {
    select: () => {
      from: (t: unknown) => Promise<
        Array<{
          id: string
          organizationId: string
          agentId: string
          slug: string
          cron: string
          enabled: boolean
          createdAt: Date
          updatedAt: Date
        }>
      >
    }
    insert: (t: unknown) => {
      values: (v: unknown) => { onConflictDoNothing: () => Promise<void> }
    }
  }

  const rules = await d.select().from(automationRules)

  for (const rule of rules) {
    await d
      .insert(automations)
      .values({
        id: rule.id, // reuse id so cross-references resolve
        organizationId: rule.organizationId,
        name: rule.slug,
        eventName: 'cron',
        action: { type: 'wake', agentId: rule.agentId, lane: 'standalone' },
        paused: !rule.enabled,
        cron: rule.cron,
        createdAt: rule.createdAt,
        updatedAt: rule.updatedAt,
      })
      .onConflictDoNothing()
  }

  // System-owned pending-decision-followup cron (US-010). Seeded once per org
  // we know about; falls back to scanning distinct orgs from automation_rules
  // when no explicit org is provided.
  const orgIds = opts?.organizationId ? [opts.organizationId] : Array.from(new Set(rules.map((r) => r.organizationId)))

  for (const organizationId of orgIds) {
    await d
      .insert(automations)
      .values({
        // id auto-generated by nanoidPrimaryKey() — uniqueness comes from
        // (organizationId, name).
        organizationId,
        name: PENDING_DECISION_FOLLOWUP_RULE_NAME,
        eventName: 'cron',
        // TODO(US-013): replace placeholder agentId with the resolved
        // system-followup agent id once dispatcher.ts can route by rule name.
        action: {
          type: 'wake',
          agentId: PENDING_DECISION_FOLLOWUP_AGENT_ID,
          lane: 'standalone',
        },
        paused: false,
        cron: PENDING_DECISION_FOLLOWUP_CRON,
      })
      .onConflictDoNothing()
  }
}
