// Auto-generated by `bun run api:types` — do not edit manually.
// Mirrors server route mounting so `hc<AppType>` gives end-to-end type safety.
// Frontend files must only use `import type { AppType }` — never a runtime import.
import type { Conversation, Message, PendingApproval } from '@modules/inbox/schema'
import { Hono } from 'hono'

function _typedApp() {
  const inboxApp = new Hono()
    .get('/conversations', (c) => c.json([] as Conversation[]))
    .get('/conversations/:id/messages', (c) => c.json([] as Message[]))
    .get('/approvals', (c) => c.json([] as PendingApproval[]))
    .post('/approvals/:id', (c) =>
      c.json({
        ok: false as boolean,
        approvalId: '' as string,
        status: '' as string,
        enqueued: false as boolean,
      }),
    )

  return new Hono().route('/api/inbox', inboxApp)
}

export type AppType = ReturnType<typeof _typedApp>
