/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as pagesTestWebRouteImport } from './pages/test-web'
import { Route as shellAuthLayoutRouteImport } from './shell/auth/layout'
import { Route as shellAppLayoutRouteImport } from './shell/app-layout'
import { Route as pagesChatDotchannelInstanceIdRouteImport } from './pages/chat.$channelInstanceId'
import { Route as DotDotModulesSettingsPagesLayoutRouteImport } from './../modules/settings/pages/layout'
import { Route as DotDotModulesInboxPagesLayoutRouteImport } from './../modules/inbox/pages/layout'
import { Route as shellHomeRedirectRouteImport } from './shell/home-redirect'
import { Route as IndexRouteImport } from './../modules/inbox/pages/index'
import { Route as DriveIndexRouteImport } from './../modules/drive/pages/index'
import { Route as ContactsIndexRouteImport } from './../modules/contacts/pages/index'
import { Route as ChannelsIndexRouteImport } from './../modules/channels/pages/index'
import { Route as AgentsIndexRouteImport } from './../modules/agents/pages/index'
import { Route as shellAuthPendingRouteImport } from './shell/auth/pending'
import { Route as shellAuthLoginRouteImport } from './shell/auth/login'
import { Route as ProfileRouteImport } from './../modules/settings/pages/profile'
import { Route as NotificationsRouteImport } from './../modules/settings/pages/notifications'
import { Route as DisplayRouteImport } from './../modules/settings/pages/display'
import { Route as AppearanceRouteImport } from './../modules/settings/pages/appearance'
import { Route as ApiKeysRouteImport } from './../modules/settings/pages/api-keys'
import { Route as AccountRouteImport } from './../modules/settings/pages/account'
import { Route as ApprovalsRouteImport } from './../modules/inbox/pages/approvals'
import { Route as IdRouteImport } from './../modules/inbox/pages/$id'
import { Route as ContactsAttributesRouteImport } from './../modules/contacts/pages/attributes'
import { Route as ContactsIdRouteImport } from './../modules/contacts/pages/$id'
import { Route as AgentsLearningsRouteImport } from './../modules/agents/pages/learnings'

const pagesTestWebRoute = pagesTestWebRouteImport.update({
  id: '/test-web',
  path: '/test-web',
  getParentRoute: () => rootRouteImport,
} as any)
const shellAuthLayoutRoute = shellAuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const shellAppLayoutRoute = shellAppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesChatDotchannelInstanceIdRoute =
  pagesChatDotchannelInstanceIdRouteImport.update({
    id: '/chat/$channelInstanceId',
    path: '/chat/$channelInstanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotModulesSettingsPagesLayoutRoute =
  DotDotModulesSettingsPagesLayoutRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => shellAppLayoutRoute,
  } as any)
const DotDotModulesInboxPagesLayoutRoute =
  DotDotModulesInboxPagesLayoutRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => shellAppLayoutRoute,
  } as any)
const shellHomeRedirectRoute = shellHomeRedirectRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DotDotModulesInboxPagesLayoutRoute,
} as any)
const DriveIndexRoute = DriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const shellAuthPendingRoute = shellAuthPendingRouteImport.update({
  id: '/auth/pending',
  path: '/auth/pending',
  getParentRoute: () => shellAuthLayoutRoute,
} as any)
const shellAuthLoginRoute = shellAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => shellAuthLayoutRoute,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DotDotModulesSettingsPagesLayoutRoute,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DotDotModulesSettingsPagesLayoutRoute,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => DotDotModulesSettingsPagesLayoutRoute,
} as any)
const AppearanceRoute = AppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => DotDotModulesSettingsPagesLayoutRoute,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DotDotModulesSettingsPagesLayoutRoute,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DotDotModulesSettingsPagesLayoutRoute,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DotDotModulesInboxPagesLayoutRoute,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DotDotModulesInboxPagesLayoutRoute,
} as any)
const ContactsAttributesRoute = ContactsAttributesRouteImport.update({
  id: '/contacts/attributes',
  path: '/contacts/attributes',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => shellAppLayoutRoute,
} as any)
const AgentsLearningsRoute = AgentsLearningsRouteImport.update({
  id: '/agents/learnings',
  path: '/agents/learnings',
  getParentRoute: () => shellAppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof shellHomeRedirectRoute
  '/test-web': typeof pagesTestWebRoute
  '/inbox': typeof DotDotModulesInboxPagesLayoutRouteWithChildren
  '/settings': typeof DotDotModulesSettingsPagesLayoutRouteWithChildren
  '/chat/$channelInstanceId': typeof pagesChatDotchannelInstanceIdRoute
  '/agents/learnings': typeof AgentsLearningsRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/attributes': typeof ContactsAttributesRoute
  '/inbox/$id': typeof IdRoute
  '/inbox/approvals': typeof ApprovalsRoute
  '/settings/account': typeof AccountRoute
  '/settings/api-keys': typeof ApiKeysRoute
  '/settings/appearance': typeof AppearanceRoute
  '/settings/display': typeof DisplayRoute
  '/settings/notifications': typeof NotificationsRoute
  '/settings/profile': typeof ProfileRoute
  '/auth/login': typeof shellAuthLoginRoute
  '/auth/pending': typeof shellAuthPendingRoute
  '/agents/': typeof AgentsIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/drive/': typeof DriveIndexRoute
  '/inbox/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof shellHomeRedirectRoute
  '/test-web': typeof pagesTestWebRoute
  '/settings': typeof DotDotModulesSettingsPagesLayoutRouteWithChildren
  '/chat/$channelInstanceId': typeof pagesChatDotchannelInstanceIdRoute
  '/agents/learnings': typeof AgentsLearningsRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/attributes': typeof ContactsAttributesRoute
  '/inbox/$id': typeof IdRoute
  '/inbox/approvals': typeof ApprovalsRoute
  '/settings/account': typeof AccountRoute
  '/settings/api-keys': typeof ApiKeysRoute
  '/settings/appearance': typeof AppearanceRoute
  '/settings/display': typeof DisplayRoute
  '/settings/notifications': typeof NotificationsRoute
  '/settings/profile': typeof ProfileRoute
  '/auth/login': typeof shellAuthLoginRoute
  '/auth/pending': typeof shellAuthPendingRoute
  '/agents': typeof AgentsIndexRoute
  '/channels': typeof ChannelsIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/drive': typeof DriveIndexRoute
  '/inbox': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof shellAppLayoutRouteWithChildren
  '/_auth': typeof shellAuthLayoutRouteWithChildren
  '/test-web': typeof pagesTestWebRoute
  '/_app/': typeof shellHomeRedirectRoute
  '/_app/inbox': typeof DotDotModulesInboxPagesLayoutRouteWithChildren
  '/_app/settings': typeof DotDotModulesSettingsPagesLayoutRouteWithChildren
  '/chat/$channelInstanceId': typeof pagesChatDotchannelInstanceIdRoute
  '/_app/agents/learnings': typeof AgentsLearningsRoute
  '/_app/contacts/$id': typeof ContactsIdRoute
  '/_app/contacts/attributes': typeof ContactsAttributesRoute
  '/_app/inbox/$id': typeof IdRoute
  '/_app/inbox/approvals': typeof ApprovalsRoute
  '/_app/settings/account': typeof AccountRoute
  '/_app/settings/api-keys': typeof ApiKeysRoute
  '/_app/settings/appearance': typeof AppearanceRoute
  '/_app/settings/display': typeof DisplayRoute
  '/_app/settings/notifications': typeof NotificationsRoute
  '/_app/settings/profile': typeof ProfileRoute
  '/_auth/auth/login': typeof shellAuthLoginRoute
  '/_auth/auth/pending': typeof shellAuthPendingRoute
  '/_app/agents/': typeof AgentsIndexRoute
  '/_app/channels/': typeof ChannelsIndexRoute
  '/_app/contacts/': typeof ContactsIndexRoute
  '/_app/drive/': typeof DriveIndexRoute
  '/_app/inbox/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-web'
    | '/inbox'
    | '/settings'
    | '/chat/$channelInstanceId'
    | '/agents/learnings'
    | '/contacts/$id'
    | '/contacts/attributes'
    | '/inbox/$id'
    | '/inbox/approvals'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/profile'
    | '/auth/login'
    | '/auth/pending'
    | '/agents/'
    | '/channels/'
    | '/contacts/'
    | '/drive/'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test-web'
    | '/settings'
    | '/chat/$channelInstanceId'
    | '/agents/learnings'
    | '/contacts/$id'
    | '/contacts/attributes'
    | '/inbox/$id'
    | '/inbox/approvals'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/profile'
    | '/auth/login'
    | '/auth/pending'
    | '/agents'
    | '/channels'
    | '/contacts'
    | '/drive'
    | '/inbox'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/test-web'
    | '/_app/'
    | '/_app/inbox'
    | '/_app/settings'
    | '/chat/$channelInstanceId'
    | '/_app/agents/learnings'
    | '/_app/contacts/$id'
    | '/_app/contacts/attributes'
    | '/_app/inbox/$id'
    | '/_app/inbox/approvals'
    | '/_app/settings/account'
    | '/_app/settings/api-keys'
    | '/_app/settings/appearance'
    | '/_app/settings/display'
    | '/_app/settings/notifications'
    | '/_app/settings/profile'
    | '/_auth/auth/login'
    | '/_auth/auth/pending'
    | '/_app/agents/'
    | '/_app/channels/'
    | '/_app/contacts/'
    | '/_app/drive/'
    | '/_app/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  shellAppLayoutRoute: typeof shellAppLayoutRouteWithChildren
  shellAuthLayoutRoute: typeof shellAuthLayoutRouteWithChildren
  pagesTestWebRoute: typeof pagesTestWebRoute
  pagesChatDotchannelInstanceIdRoute: typeof pagesChatDotchannelInstanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-web': {
      id: '/test-web'
      path: '/test-web'
      fullPath: '/test-web'
      preLoaderRoute: typeof pagesTestWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof shellAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof shellAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$channelInstanceId': {
      id: '/chat/$channelInstanceId'
      path: '/chat/$channelInstanceId'
      fullPath: '/chat/$channelInstanceId'
      preLoaderRoute: typeof pagesChatDotchannelInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DotDotModulesSettingsPagesLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof DotDotModulesInboxPagesLayoutRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof shellHomeRedirectRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof DotDotModulesInboxPagesLayoutRoute
    }
    '/_app/drive/': {
      id: '/_app/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof DriveIndexRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/channels/': {
      id: '/_app/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_auth/auth/pending': {
      id: '/_auth/auth/pending'
      path: '/auth/pending'
      fullPath: '/auth/pending'
      preLoaderRoute: typeof shellAuthPendingRouteImport
      parentRoute: typeof shellAuthLayoutRoute
    }
    '/_auth/auth/login': {
      id: '/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof shellAuthLoginRouteImport
      parentRoute: typeof shellAuthLayoutRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof DotDotModulesSettingsPagesLayoutRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof DotDotModulesSettingsPagesLayoutRoute
    }
    '/_app/settings/display': {
      id: '/_app/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof DotDotModulesSettingsPagesLayoutRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppearanceRouteImport
      parentRoute: typeof DotDotModulesSettingsPagesLayoutRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof DotDotModulesSettingsPagesLayoutRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof DotDotModulesSettingsPagesLayoutRoute
    }
    '/_app/inbox/approvals': {
      id: '/_app/inbox/approvals'
      path: '/approvals'
      fullPath: '/inbox/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof DotDotModulesInboxPagesLayoutRoute
    }
    '/_app/inbox/$id': {
      id: '/_app/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof DotDotModulesInboxPagesLayoutRoute
    }
    '/_app/contacts/attributes': {
      id: '/_app/contacts/attributes'
      path: '/contacts/attributes'
      fullPath: '/contacts/attributes'
      preLoaderRoute: typeof ContactsAttributesRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
    '/_app/agents/learnings': {
      id: '/_app/agents/learnings'
      path: '/agents/learnings'
      fullPath: '/agents/learnings'
      preLoaderRoute: typeof AgentsLearningsRouteImport
      parentRoute: typeof shellAppLayoutRoute
    }
  }
}

interface DotDotModulesInboxPagesLayoutRouteChildren {
  IdRoute: typeof IdRoute
  ApprovalsRoute: typeof ApprovalsRoute
  IndexRoute: typeof IndexRoute
}

const DotDotModulesInboxPagesLayoutRouteChildren: DotDotModulesInboxPagesLayoutRouteChildren =
  {
    IdRoute: IdRoute,
    ApprovalsRoute: ApprovalsRoute,
    IndexRoute: IndexRoute,
  }

const DotDotModulesInboxPagesLayoutRouteWithChildren =
  DotDotModulesInboxPagesLayoutRoute._addFileChildren(
    DotDotModulesInboxPagesLayoutRouteChildren,
  )

interface DotDotModulesSettingsPagesLayoutRouteChildren {
  AccountRoute: typeof AccountRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AppearanceRoute: typeof AppearanceRoute
  DisplayRoute: typeof DisplayRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
}

const DotDotModulesSettingsPagesLayoutRouteChildren: DotDotModulesSettingsPagesLayoutRouteChildren =
  {
    AccountRoute: AccountRoute,
    ApiKeysRoute: ApiKeysRoute,
    AppearanceRoute: AppearanceRoute,
    DisplayRoute: DisplayRoute,
    NotificationsRoute: NotificationsRoute,
    ProfileRoute: ProfileRoute,
  }

const DotDotModulesSettingsPagesLayoutRouteWithChildren =
  DotDotModulesSettingsPagesLayoutRoute._addFileChildren(
    DotDotModulesSettingsPagesLayoutRouteChildren,
  )

interface shellAppLayoutRouteChildren {
  shellHomeRedirectRoute: typeof shellHomeRedirectRoute
  DotDotModulesInboxPagesLayoutRoute: typeof DotDotModulesInboxPagesLayoutRouteWithChildren
  DotDotModulesSettingsPagesLayoutRoute: typeof DotDotModulesSettingsPagesLayoutRouteWithChildren
  AgentsLearningsRoute: typeof AgentsLearningsRoute
  ContactsIdRoute: typeof ContactsIdRoute
  ContactsAttributesRoute: typeof ContactsAttributesRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  DriveIndexRoute: typeof DriveIndexRoute
}

const shellAppLayoutRouteChildren: shellAppLayoutRouteChildren = {
  shellHomeRedirectRoute: shellHomeRedirectRoute,
  DotDotModulesInboxPagesLayoutRoute:
    DotDotModulesInboxPagesLayoutRouteWithChildren,
  DotDotModulesSettingsPagesLayoutRoute:
    DotDotModulesSettingsPagesLayoutRouteWithChildren,
  AgentsLearningsRoute: AgentsLearningsRoute,
  ContactsIdRoute: ContactsIdRoute,
  ContactsAttributesRoute: ContactsAttributesRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  DriveIndexRoute: DriveIndexRoute,
}

const shellAppLayoutRouteWithChildren = shellAppLayoutRoute._addFileChildren(
  shellAppLayoutRouteChildren,
)

interface shellAuthLayoutRouteChildren {
  shellAuthLoginRoute: typeof shellAuthLoginRoute
  shellAuthPendingRoute: typeof shellAuthPendingRoute
}

const shellAuthLayoutRouteChildren: shellAuthLayoutRouteChildren = {
  shellAuthLoginRoute: shellAuthLoginRoute,
  shellAuthPendingRoute: shellAuthPendingRoute,
}

const shellAuthLayoutRouteWithChildren = shellAuthLayoutRoute._addFileChildren(
  shellAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  shellAppLayoutRoute: shellAppLayoutRouteWithChildren,
  shellAuthLayoutRoute: shellAuthLayoutRouteWithChildren,
  pagesTestWebRoute: pagesTestWebRoute,
  pagesChatDotchannelInstanceIdRoute: pagesChatDotchannelInstanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
